### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by Gustry** [riccardoklinger/qgis2web#7]
Since the last update yesterday, I have this error everytime when I launch qgis : 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/etienne/.qgis2/python/plugins/qgis2web/__init__.py", line 23, in classFactory
    from qgis2web import qgis2web
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/etienne/.qgis2/python/plugins/qgis2web/qgis2web.py", line 28, in 
    from maindialog import MainDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/etienne/.qgis2/python/plugins/qgis2web/maindialog.py", line 134
    subitem = TreeSettingItem(item, self.paramsTreeOL, param, value, dlg)
          ^
IndentationError: expected an indented block
```

**Comment by tomchadwin** [comment]
Many apologies. That does look like a plain bug. I'll try to sort it out as soon as I can, but it might not be until tomorrow. Downgrade to the previous version until I can do the fix.

**Comment by tomchadwin** [comment]
Fixed in https://github.com/tomchadwin/qgis2web/tree/master, and pushed as 0.12.2 to QGIS plugin repo
